{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- $metadata := merge dict (.Values.restapi.metadata | default dict) (dict "labels" (fromYaml (include "slurm.labels" $))) -}}
{{- $podSpec := .Values.restapi.podSpec | default dict -}}
{{- $imagePullSecrets := concat list ($podSpec | dig "imagePullSecrets" list) (.Values.imagePullSecrets | default list) -}}
{{- $_ := set $podSpec "imagePullSecrets" $imagePullSecrets -}}
{{- $priorityClassName := $podSpec | dig "priorityClassName" "" | default (include "slurm.priorityClassName" . | toString) -}}
{{- $_ := set $podSpec "priorityClassName" $priorityClassName -}}
{{- $podTemplate := dict "metadata" $metadata "spec" $podSpec -}}
{{- $slurmrestd := .Values.restapi.slurmrestd | default dict -}}
---
apiVersion: slinky.slurm.net/v1beta1
kind: RestApi
metadata:
  name: {{ include "slurm.fullname" . }}
  namespace: {{ include "slurm.namespace" . }}
{{- with $metadata }}
  {{- toYaml . | nindent 2 }}
{{- end }}{{- /* with $metadata */}}
spec:
  controllerRef:
    name: {{ include "slurm.fullname" . }}
  replicas: {{ .Values.restapi.replicas }}
  slurmrestd:
    {{- $_ := set $slurmrestd "imagePullPolicy" (get $slurmrestd "imagePullPolicy" | default $.Values.imagePullPolicy) -}}
    {{- include "slurm.format-container" $slurmrestd | nindent 4 }}
  {{- include "slurm.format-podTemplate" $podTemplate | nindent 2 }}
  {{- with .Values.restapi.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* with Values.restapi.service */}}
