apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik-ingress
  namespace: workload
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: interactive-session
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: slurm
      podSelector:
        matchLabels:
          app: hpc-portal
    - namespaceSelector:
        matchLabels:
          sandbox.zone: control-plane
      podSelector:
        matchLabels:
          app: hpc-portal
    ports:
    - protocol: TCP
      port: 8888
