FROM ghcr.io/slinkyproject/slurmd:25.11-ubuntu24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    sssd \
    sssd-ldap \
    ldap-utils \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/sssd.supervisor.conf /etc/supervisor/conf.d/sssd.conf
COPY scripts/slurmd-entrypoint.sh /entrypoint-wrapper.sh
RUN chmod +x /entrypoint-wrapper.sh

ENTRYPOINT ["/entrypoint-wrapper.sh"]
