uid nslcd
gid nslcd

uri ldap://openldap-server

base dc=sandbox,dc=local

binddn cn=admin,dc=sandbox,dc=local
bindpw adminpass

base passwd ou=Users,dc=sandbox,dc=local
base group ou=Groups,dc=sandbox,dc=local

filter passwd (objectClass=posixAccount)
filter group (objectClass=posixGroup)

map passwd homeDirectory homeDirectory
map passwd loginShell loginShell
