[domain/sandbox.local]
id_provider = ldap
auth_provider = ldap

ldap_uri = ldap://openldap-server
ldap_search_base = dc=sandbox,dc=local

# ADD THESE - bind as admin to read the directory
ldap_default_bind_dn = cn=admin,dc=sandbox,dc=local
ldap_default_authtok = adminpass

ldap_user_search_base = ou=Users,dc=sandbox,dc=local
ldap_user_object_class = posixAccount
ldap_user_name = uid

ldap_group_search_base = ou=Groups,dc=sandbox,dc=local
ldap_group_object_class = posixGroup
ldap_group_member = memberUid
ldap_tls_reqcert = never

enumerate = false
cache_credentials = true
