[sssd]
config_file_version = 2
services = nss, pam
domains = sandbox.local

[nss]
filter_groups = root,slurm,munge
filter_users = root,slurm,munge
reconnection_retries = 3

[pam]

[domain/sandbox.local]
id_provider = ldap
auth_provider = ldap

# Network name matching your container service name in docker-compose
ldap_uri = ldap://127.0.0.1
ldap_search_base = dc=sandbox,dc=local

ldap_user_search_base = ou=Users,dc=sandbox,dc=local
ldap_user_object_class = posixAccount
ldap_user_name = uid

ldap_group_search_base = ou=Groups,dc=sandbox,dc=local
ldap_group_object_class = posixGroup
ldap_group_member = memberUid
ldap_tls_reqcert = never

# Important settings for test containers
enumerate = false
cache_credentials = true
