kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane  # The master node
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        feature-gates: KubeletInUserNamespace=true
  extraMounts:
  - hostPath: /home/khemi/workspace/ai_sandbox/storage
    containerPath: /mnt/storage
- role: worker         # Compute node 1
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        feature-gates: KubeletInUserNamespace=true
  extraMounts:
  - hostPath: /home/khemi/workspace/ai_sandbox/storage
    containerPath: /mnt/storage
- role: worker         # Compute node 2
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        feature-gates: KubeletInUserNamespace=true
  extraMounts:
  - hostPath: /home/khemi/workspace/ai_sandbox/storage
    containerPath: /mnt/storage
- role: worker         # Dedicated interactive compute node (kind-worker3)
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        feature-gates: KubeletInUserNamespace=true
  extraMounts:
  - hostPath: /home/khemi/workspace/ai_sandbox/storage
    containerPath: /mnt/storage
