apiVersion: v1
kind: PersistentVolume
metadata:
  name: slinky-storage-pv
  namespace: slurm
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slinky-storage-pvc
  namespace: slurm
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: slinky-storage-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slurm-state-pv
  namespace: slurm
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/slurm-state
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-state-pvc
  namespace: slurm
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: slurm-state-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workload-storage-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slinky-storage-pvc
  namespace: workload
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: workload-storage-pv
