admission:
  managedNamespaces:
    - workload
  nodeSelector:
    kubernetes.io/hostname: ai-control
  tolerations:
    - key: "slinky.slurm.net/managed-node"
      operator: "Exists"
      effect: "NoExecute"
controllers:
  nodeSelector:
    kubernetes.io/hostname: ai-control
  tolerations:
    - key: "slinky.slurm.net/managed-node"
      operator: "Exists"
      effect: "NoExecute"
scheduler:
  nodeSelector:
    kubernetes.io/hostname: ai-control
  tolerations:
    - key: "slinky.slurm.net/managed-node"
      operator: "Exists"
      effect: "NoExecute"
sharedConfig:
  slurmRestApi: http://slurm-restapi.slurm:6820
  slurmJwtSecret: slurm-bridge-token
schedulerConfig:
  partition: interactive
