[program:sssd]
command=/usr/sbin/sssd -i -d 3 --config /run/sssd/sssd.conf
autostart=true
autorestart=true
priority=5
startsecs=3
stdout_logfile=/var/log/sssd/sssd-supervisor.log
stderr_logfile=/var/log/sssd/sssd-supervisor.log
